name: CI Pipeline
 
on:
  push:
    branches:
      - master  # Triggers on pushes to the master branch
  pull_request:
    branches:
      - master
 
jobs:
  build-and-test:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Clear cache
      run: |
        rm -rf node_modules
        npm cache clean --force
   
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.15.0'
 
    - name: Install dependencies
      run: npm install --legacy-peer-deps --force
 

    - name: Run Dyson homepage feature and push results to Cypress Cloud
      run: npx cypress run --spec "cypress/e2e/4-features/dyson-homepage.feature" --record --key 811fea40-deae-4afb-aa81-46621f6da712

